//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.FunctionGraffiti.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class index_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal index_cshtml() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.FunctionGraffiti.App_LocalResources.index.cshtml", typeof(index_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;a href=&quot;/Ploter&quot; title=&quot;Go to Ploter!&quot;&gt;&lt;img src=&quot;/Content/Images/Ploter.png&quot; alt=&quot;Ploter&quot; /&gt;&lt;/a&gt; 的本地化字符串。
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function Graffiti 的本地化字符串。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span style=&quot;color: white; font-size: small; background-color: red; padding: 5px 10px;&quot;&gt;Graph functions online!&lt;/span&gt;&lt;span style=&quot;margin-left: 100px; font-size: small; display: none;&quot;&gt;&lt;a style=&quot;color: yellow; display: none;&quot; href=&quot;/Ploter&quot;&gt;Go to Ploter!&lt;/a&gt;&lt;/span&gt; 的本地化字符串。
        /// </summary>
        public static string ApplicationNameRemark {
            get {
                return ResourceManager.GetString("ApplicationNameRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        public static string AutoYRangeLabel {
            get {
                return ResourceManager.GetString("AutoYRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charming Curve. 的本地化字符串。
        /// </summary>
        public static string CharmingCurve {
            get {
                return ResourceManager.GetString("CharmingCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How to draw a unit circle? 的本地化字符串。
        /// </summary>
        public static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to see its graph 的本地化字符串。
        /// </summary>
        public static string ClickToSeeGraph {
            get {
                return ResourceManager.GetString("ClickToSeeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add comment 的本地化字符串。
        /// </summary>
        public static string CommentTitle {
            get {
                return ResourceManager.GetString("CommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Darts. 的本地化字符串。
        /// </summary>
        public static string Darts {
            get {
                return ResourceManager.GetString("Darts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function(s): 的本地化字符串。
        /// </summary>
        public static string FunctionsTitle {
            get {
                return ResourceManager.GetString("FunctionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graph! (G) 的本地化字符串。
        /// </summary>
        public static string GraphButtonText {
            get {
                return ResourceManager.GetString("GraphButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input into the function(s) text box: 的本地化字符串。
        /// </summary>
        public static string InputFunctions {
            get {
                return ResourceManager.GetString("InputFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type one or more equations into the box above and click the Graph button. Separate multiple equations with semicolons. 的本地化字符串。
        /// </summary>
        public static string InstructionsDesc1 {
            get {
                return ResourceManager.GetString("InstructionsDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Below is some interesting examples, you can click on them to see their graph. 的本地化字符串。
        /// </summary>
        public static string InstructionsDesc2 {
            get {
                return ResourceManager.GetString("InstructionsDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Have a nice journey! 的本地化字符串。
        /// </summary>
        public static string InstructionsDesc3 {
            get {
                return ResourceManager.GetString("InstructionsDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instructions 的本地化字符串。
        /// </summary>
        public static string InstructionsTitle {
            get {
                return ResourceManager.GetString("InstructionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冏. 的本地化字符串。
        /// </summary>
        public static string Jiong {
            get {
                return ResourceManager.GetString("Jiong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Link (L) 的本地化字符串。
        /// </summary>
        public static string LinkButtonText {
            get {
                return ResourceManager.GetString("LinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link To This Graph: 的本地化字符串。
        /// </summary>
        public static string LinkLabelText {
            get {
                return ResourceManager.GetString("LinkLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;a href=&quot;http://www.zizhujy.com/blog/post/2011/10/10/Alphabetic-list-of-functions-supported-by-Online-Function-Graffiti.aspx&quot; title=&quot;List of all functions&quot; target=&quot;_blank&quot;&gt;List of all functions&lt;/a&gt; 的本地化字符串。
        /// </summary>
        public static string ListOfFunctions {
            get {
                return ResourceManager.GetString("ListOfFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 力新博客 的本地化字符串。
        /// </summary>
        public static string LiXinBlog {
            get {
                return ResourceManager.GetString("LiXinBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;h1&gt;Function Graffiti &lt;span style=&quot;font-size: xx-small; color: Red;&quot;&gt;graph functions online!&lt;/span&gt;&lt;/h1&gt;
        ///&lt;p&gt;&lt;a href=&quot;http://www.zizhujy.com/blog/page/Online-Function-Graffiti!.aspx&quot; target=&quot;_blank&quot;&gt;About Function Graffiti.&lt;/a&gt;&lt;/p&gt; 的本地化字符串。
        /// </summary>
        public static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nappe. 的本地化字符串。
        /// </summary>
        public static string Nappe {
            get {
                return ResourceManager.GetString("Nappe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version is available with implicit function plotting support! 的本地化字符串。
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Function Graffiti - The best function grapher! Draw functions easily. 的本地化字符串。
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optional. The default value is 500, maximum is 10000. The more the points number is, the more accurate the graph is. 的本地化字符串。
        /// </summary>
        public static string PointsCountTip {
            get {
                return ResourceManager.GetString("PointsCountTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Points:  的本地化字符串。
        /// </summary>
        public static string PointsCountTitle {
            get {
                return ResourceManager.GetString("PointsCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 for providing this 的本地化字符串。
        /// </summary>
        public static string Provide {
            get {
                return ResourceManager.GetString("Provide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset (R) 的本地化字符串。
        /// </summary>
        public static string ResetButtonText {
            get {
                return ResourceManager.GetString("ResetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;p&gt;Another smoke &lt;a href=&quot;javascript:jGraffiti.graph(&apos;sin(x) + (1/100)*cos(100*x);&apos;, -0.1, 0.1, -0.1, 0.1, null, null, 500, false);&quot;
        ///            title=&quot;Another smoke&quot; target=&quot;_self&quot;&gt;Click here to see its graph&lt;/a&gt;&lt;/p&gt;
        ///    &lt;p style=&quot;text-indent: 2em;&quot;&gt;Input into the function(s) text box:&lt;/p&gt;
        ///    &lt;pre class=&quot;brush: javascript&quot;&gt;sin(x) + (1/100)*cos(100*x);&lt;/pre&gt; 的本地化字符串。
        /// </summary>
        public static string Samples {
            get {
                return ResourceManager.GetString("Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale of t axies:  的本地化字符串。
        /// </summary>
        public static string ScaleOfTAxiesTitle {
            get {
                return ResourceManager.GetString("ScaleOfTAxiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale of x axies:  的本地化字符串。
        /// </summary>
        public static string ScaleOfXAxiesTitle {
            get {
                return ResourceManager.GetString("ScaleOfXAxiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale of y axies:  的本地化字符串。
        /// </summary>
        public static string ScaleOfYAxiesTitle {
            get {
                return ResourceManager.GetString("ScaleOfYAxiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Function Grapher. Graphing Calculator. Graph functions immediately. Graph online. Multi-functions support, no upper limit for the number of functions, you can graph as many functions as you wish in a single graph! Many funny samples! Draw functions easily. 的本地化字符串。
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function graffiti, graffiti, function graph, function grapher, grapher, plot, graphs online, graphs on-line, online function grapher, 2d function grapher, graphing calculator 的本地化字符串。
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share (S) 的本地化字符串。
        /// </summary>
        public static string ShareButtonText {
            get {
                return ResourceManager.GetString("ShareButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legend 的本地化字符串。
        /// </summary>
        public static string ShowLegend {
            get {
                return ResourceManager.GetString("ShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smoke. 的本地化字符串。
        /// </summary>
        public static string Smoke {
            get {
                return ResourceManager.GetString("Smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spaghetti. 的本地化字符串。
        /// </summary>
        public static string Spaghetti {
            get {
                return ResourceManager.GetString("Spaghetti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spiral. 的本地化字符串。
        /// </summary>
        public static string Spiral {
            get {
                return ResourceManager.GetString("Spiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks 的本地化字符串。
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div id=&quot;disqus_thread&quot;&gt;&lt;/div&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        ///    var disqus_shortname = &apos;zizhujy&apos;; // required: replace example with your forum shortname
        ///
        ///    /* * * DON&apos;T EDIT BELOW THIS LINE * * */
        ///    (function() {
        ///        var dsq = document.createElement(&apos;script&apos;); dsq.type = &apos;text/javascript&apos;; dsq.async = true;
        ///        dsq.src = &apos;http://&apos; + disqus_shortname + &apos;.disqus.com/embed.js&apos;;
        ///        (document.getElements [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ThirdPartyCommentCode {
            get {
                return ResourceManager.GetString("ThirdPartyCommentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tight encirclement. 的本地化字符串。
        /// </summary>
        public static string TightEncirclement {
            get {
                return ResourceManager.GetString("TightEncirclement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please use lower case x or y to indicate the independent variable, use x^2 to indicate square, x^3 to indicate cubic, and so forth. You can omit the denpendent variable &quot;y = &quot; part, and use the semicolon &quot;;&quot; to separate multiply functions. 的本地化字符串。
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Water stream. 的本地化字符串。
        /// </summary>
        public static string TitleOfWaterStream {
            get {
                return ResourceManager.GetString("TitleOfWaterStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To 的本地化字符串。
        /// </summary>
        public static string ToTitle {
            get {
                return ResourceManager.GetString("ToTitle", resourceCulture);
            }
        }
    }
}
