//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.FunctionGraffiti.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class index_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal index_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.FunctionGraffiti.App_LocalResources.index.cshtml", typeof(index_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;/Ploter&quot; title=&quot;Go to Ploter!&quot;&gt;&lt;img src=&quot;/Content/Images/Ploter.png&quot; alt=&quot;Ploter&quot; /&gt;&lt;/a&gt;.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Graffiti.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color: white; font-size: small; background-color: red; padding: 5px 10px;&quot;&gt;Graph functions online!&lt;/span&gt;&lt;span style=&quot;margin-left: 100px; font-size: small; display: none;&quot;&gt;&lt;a style=&quot;color: yellow; display: none;&quot; href=&quot;/Ploter&quot;&gt;Go to Ploter!&lt;/a&gt;&lt;/span&gt;.
        /// </summary>
        public static string ApplicationNameRemark {
            get {
                return ResourceManager.GetString("ApplicationNameRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string AutoYRangeLabel {
            get {
                return ResourceManager.GetString("AutoYRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charming Curve..
        /// </summary>
        public static string CharmingCurve {
            get {
                return ResourceManager.GetString("CharmingCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to draw a unit circle?.
        /// </summary>
        public static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see its graph.
        /// </summary>
        public static string ClickToSeeGraph {
            get {
                return ResourceManager.GetString("ClickToSeeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        public static string CommentTitle {
            get {
                return ResourceManager.GetString("CommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darts..
        /// </summary>
        public static string Darts {
            get {
                return ResourceManager.GetString("Darts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function(s):.
        /// </summary>
        public static string FunctionsTitle {
            get {
                return ResourceManager.GetString("FunctionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph! (G).
        /// </summary>
        public static string GraphButtonText {
            get {
                return ResourceManager.GetString("GraphButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input into the function(s) text box:.
        /// </summary>
        public static string InputFunctions {
            get {
                return ResourceManager.GetString("InputFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type one or more equations into the box above and click the Graph button. Separate multiple equations with semicolons..
        /// </summary>
        public static string InstructionsDesc1 {
            get {
                return ResourceManager.GetString("InstructionsDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below is some interesting examples, you can click on them to see their graph..
        /// </summary>
        public static string InstructionsDesc2 {
            get {
                return ResourceManager.GetString("InstructionsDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a nice journey!.
        /// </summary>
        public static string InstructionsDesc3 {
            get {
                return ResourceManager.GetString("InstructionsDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string InstructionsTitle {
            get {
                return ResourceManager.GetString("InstructionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冏..
        /// </summary>
        public static string Jiong {
            get {
                return ResourceManager.GetString("Jiong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Link (L).
        /// </summary>
        public static string LinkButtonText {
            get {
                return ResourceManager.GetString("LinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link To This Graph:.
        /// </summary>
        public static string LinkLabelText {
            get {
                return ResourceManager.GetString("LinkLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;http://www.zizhujy.com/blog/post/2011/10/10/Alphabetic-list-of-functions-supported-by-Online-Function-Graffiti.aspx&quot; title=&quot;List of all functions&quot; target=&quot;_blank&quot;&gt;List of all functions&lt;/a&gt;.
        /// </summary>
        public static string ListOfFunctions {
            get {
                return ResourceManager.GetString("ListOfFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 力新博客.
        /// </summary>
        public static string LiXinBlog {
            get {
                return ResourceManager.GetString("LiXinBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Function Graffiti &lt;span style=&quot;font-size: xx-small; color: Red;&quot;&gt;graph functions online!&lt;/span&gt;&lt;/h1&gt;
        ///&lt;p&gt;&lt;a href=&quot;http://www.zizhujy.com/blog/page/Online-Function-Graffiti!.aspx&quot; target=&quot;_blank&quot;&gt;About Function Graffiti.&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nappe..
        /// </summary>
        public static string Nappe {
            get {
                return ResourceManager.GetString("Nappe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available with implicit function plotting support!.
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Function Graffiti - The best function grapher! Draw functions easily..
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. The default value is 500, maximum is 10000. The more the points number is, the more accurate the graph is..
        /// </summary>
        public static string PointsCountTip {
            get {
                return ResourceManager.GetString("PointsCountTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points: .
        /// </summary>
        public static string PointsCountTitle {
            get {
                return ResourceManager.GetString("PointsCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for providing this.
        /// </summary>
        public static string Provide {
            get {
                return ResourceManager.GetString("Provide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset (R).
        /// </summary>
        public static string ResetButtonText {
            get {
                return ResourceManager.GetString("ResetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Another smoke &lt;a href=&quot;javascript:jGraffiti.graph(&apos;sin(x) + (1/100)*cos(100*x);&apos;, -0.1, 0.1, -0.1, 0.1, null, null, 500, false);&quot;
        ///            title=&quot;Another smoke&quot; target=&quot;_self&quot;&gt;Click here to see its graph&lt;/a&gt;&lt;/p&gt;
        ///    &lt;p style=&quot;text-indent: 2em;&quot;&gt;Input into the function(s) text box:&lt;/p&gt;
        ///    &lt;pre class=&quot;brush: javascript&quot;&gt;sin(x) + (1/100)*cos(100*x);&lt;/pre&gt;.
        /// </summary>
        public static string Samples {
            get {
                return ResourceManager.GetString("Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale of t axies: .
        /// </summary>
        public static string ScaleOfTAxiesTitle {
            get {
                return ResourceManager.GetString("ScaleOfTAxiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale of x axies: .
        /// </summary>
        public static string ScaleOfXAxiesTitle {
            get {
                return ResourceManager.GetString("ScaleOfXAxiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale of y axies: .
        /// </summary>
        public static string ScaleOfYAxiesTitle {
            get {
                return ResourceManager.GetString("ScaleOfYAxiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Function Grapher. Graphing Calculator. Graph functions immediately. Graph online. Multi-functions support, no upper limit for the number of functions, you can graph as many functions as you wish in a single graph! Many funny samples! Draw functions easily..
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function graffiti, graffiti, function graph, function grapher, grapher, plot, graphs online, graphs on-line, online function grapher, 2d function grapher, graphing calculator.
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share (S).
        /// </summary>
        public static string ShareButtonText {
            get {
                return ResourceManager.GetString("ShareButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string ShowLegend {
            get {
                return ResourceManager.GetString("ShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke..
        /// </summary>
        public static string Smoke {
            get {
                return ResourceManager.GetString("Smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaghetti..
        /// </summary>
        public static string Spaghetti {
            get {
                return ResourceManager.GetString("Spaghetti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiral..
        /// </summary>
        public static string Spiral {
            get {
                return ResourceManager.GetString("Spiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;disqus_thread&quot;&gt;&lt;/div&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        ///    var disqus_shortname = &apos;zizhujy&apos;; // required: replace example with your forum shortname
        ///
        ///    /* * * DON&apos;T EDIT BELOW THIS LINE * * */
        ///    (function() {
        ///        var dsq = document.createElement(&apos;script&apos;); dsq.type = &apos;text/javascript&apos;; dsq.async = true;
        ///        dsq.src = &apos;http://&apos; + disqus_shortname + &apos;.disqus.com/embed.js&apos;;
        ///        (document.getElements [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ThirdPartyCommentCode {
            get {
                return ResourceManager.GetString("ThirdPartyCommentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tight encirclement..
        /// </summary>
        public static string TightEncirclement {
            get {
                return ResourceManager.GetString("TightEncirclement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use lower case x or y to indicate the independent variable, use x^2 to indicate square, x^3 to indicate cubic, and so forth. You can omit the denpendent variable &quot;y = &quot; part, and use the semicolon &quot;;&quot; to separate multiply functions..
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water stream..
        /// </summary>
        public static string TitleOfWaterStream {
            get {
                return ResourceManager.GetString("TitleOfWaterStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string ToTitle {
            get {
                return ResourceManager.GetString("ToTitle", resourceCulture);
            }
        }
    }
}
