//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.FunctionGrapher.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class funCanvasWrapper_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal funCanvasWrapper_cshtml() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.FunctionGrapher.App_LocalResources.funCanvasWrapper.cshtml", typeof(funCanvasWrapper_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 无广告版本 的本地化字符串。
        /// </summary>
        public static string AdsFree {
            get {
                return ResourceManager.GetString("AdsFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script async src=&quot;http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js&quot;&gt;&lt;/script&gt;
        ///&lt;!-- New version of Fun Grapher --&gt;
        ///&lt;ins class=&quot;adsbygoogle&quot;
        ///     style=&quot;display:inline-block;width:336px;height:280px&quot;
        ///     data-ad-client=&quot;ca-pub-9332882982479681&quot;
        ///     data-ad-slot=&quot;7322914588&quot;&gt;&lt;/ins&gt;
        ///&lt;script&gt;
        ///(adsbygoogle = window.adsbygoogle || []).push({});
        ///&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string AdZone {
            get {
                return ResourceManager.GetString("AdZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 函数涂鸦板 &lt;span style=&quot;color: red; font-weight: normal; font-size: small;&quot;&gt;在线函数画图，支持隐函数、不等式！&lt;/span&gt; 的本地化字符串。
        /// </summary>
        public static string BannerTitle {
            get {
                return ResourceManager.GetString("BannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除全部 的本地化字符串。
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string CloseLinkDialog {
            get {
                return ResourceManager.GetString("CloseLinkDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭信息窗口 的本地化字符串。
        /// </summary>
        public static string CloseMsg {
            get {
                return ResourceManager.GetString("CloseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭帮助 的本地化字符串。
        /// </summary>
        public static string CloseTips {
            get {
                return ResourceManager.GetString("CloseTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待一个关闭的花括号 &quot;}&quot; 。 的本地化字符串。
        /// </summary>
        public static string CLOSING_BRACE_EXPECTED {
            get {
                return ResourceManager.GetString("CLOSING_BRACE_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待一个关闭的括号 &quot;)&quot; 。 的本地化字符串。
        /// </summary>
        public static string CLOSING_PARENTHESIS_EXPECTED {
            get {
                return ResourceManager.GetString("CLOSING_PARENTHESIS_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待一个逗号 &quot;,&quot;  。 的本地化字符串。
        /// </summary>
        public static string COMMA_EXPECTED {
            get {
                return ResourceManager.GetString("COMMA_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待一个常量值 (如 PI) 。 的本地化字符串。
        /// </summary>
        public static string CONSTANT_VALUE_EXPECTED {
            get {
                return ResourceManager.GetString("CONSTANT_VALUE_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相关输入 的本地化字符串。
        /// </summary>
        public static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待因变量 x 。 的本地化字符串。
        /// </summary>
        public static string DEPENDENT_VAR_X_EXPECTED {
            get {
                return ResourceManager.GetString("DEPENDENT_VAR_X_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待因变量 y 。 的本地化字符串。
        /// </summary>
        public static string DEPENDENT_VAR_Y_EXPECTED {
            get {
                return ResourceManager.GetString("DEPENDENT_VAR_Y_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待一个数字 (如 123.123) 。 的本地化字符串。
        /// </summary>
        public static string DIGITAL_NUMBER_EXPECTED {
            get {
                return ResourceManager.GetString("DIGITAL_NUMBER_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在计算 的本地化字符串。
        /// </summary>
        public static string Drawing {
            get {
                return ResourceManager.GetString("Drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请稍等片刻，正在努力地计算中…… 的本地化字符串。
        /// </summary>
        public static string DrawingDesc {
            get {
                return ResourceManager.GetString("DrawingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待输入结束。 的本地化字符串。
        /// </summary>
        public static string END_OF_SOURCE_EXPECTED {
            get {
                return ResourceManager.GetString("END_OF_SOURCE_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待一个等于号  &apos;=&apos; 。 的本地化字符串。
        /// </summary>
        public static string EQUAL_SIGN_EXPECTED {
            get {
                return ResourceManager.GetString("EQUAL_SIGN_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入有些错误： 的本地化字符串。
        /// </summary>
        public static string ErrorList {
            get {
                return ResourceManager.GetString("ErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待一个赋值符号 &quot;=&quot; 。 的本地化字符串。
        /// </summary>
        public static string EVALUATION_OPERATOR_EXPECTED {
            get {
                return ResourceManager.GetString("EVALUATION_OPERATOR_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 示例 的本地化字符串。
        /// </summary>
        public static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;h2&gt;趣涂函数涂鸦板使用方法&lt;/h2&gt;
        ///&lt;h3&gt;快速示例：&lt;/h3&gt;
        ///&lt;ul&gt;
        ///	&lt;li&gt;&lt;a href=&quot;javascript:FunGrapher.Example([&apos;y=x&apos;, &apos;y=2x&apos;]);&quot;&gt;基本示例&lt;/a&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;a href=&quot;javascript:FunGrapher.Example([&apos;y=(x-5)^3&apos;, &apos;y=-x\\left\\{0&lt;x&lt;2\\sqrt{2}\\right\\}&apos;, &apos;y=x\\left\\{-2\\sqrt{2}&lt;x&lt;0\\right\\}&apos;, &apos;x=4\\cos (t);y=4\\sin (t)&apos;, &apos;y=\\left|x+sin\\left(x\\right)\\right|&apos;]);&quot;&gt;高级示例&lt;/a&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;a href=&quot;javascript:FunGrapher.Example([&apos;x^2+y^2=10&apos;, &apos;tan(x)=sin(y)&apos;, &apos;&apos;]);&quot;&gt;画隐函数&lt;/a&gt; （需要耗费多一点时间，请耐心等待……）&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;h3&gt;迷你函数图库：&lt;/h3&gt;
        ///&lt;ul&gt;
        ///	&lt;li&gt;&lt;a href [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ExamplesContent {
            get {
                return ResourceManager.GetString("ExamplesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换全屏 的本地化字符串。
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待一个函数名 (如 sin 或 cos) 。 的本地化字符串。
        /// </summary>
        public static string FUNCTION_EXPECTED {
            get {
                return ResourceManager.GetString("FUNCTION_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入函数表达式： 的本地化字符串。
        /// </summary>
        public static string FunctionsTitle {
            get {
                return ResourceManager.GetString("FunctionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 函数涂鸦艺术 的本地化字符串。
        /// </summary>
        public static string FunGrapherArt {
            get {
                return ResourceManager.GetString("FunGrapherArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前图形链接： 的本地化字符串。
        /// </summary>
        public static string GetLinkMessageTitle {
            get {
                return ResourceManager.GetString("GetLinkMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当前图形的链接 的本地化字符串。
        /// </summary>
        public static string GetLinkTitle {
            get {
                return ResourceManager.GetString("GetLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作图 的本地化字符串。
        /// </summary>
        public static string GraphButtonText {
            get {
                return ResourceManager.GetString("GraphButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 索引 的本地化字符串。
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待在 LaTex 命令中的结尾的花括号： &quot;\\}&quot;。 的本地化字符串。
        /// </summary>
        public static string LATEX_CLOSING_BRACE_EXPECTED {
            get {
                return ResourceManager.GetString("LATEX_CLOSING_BRACE_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待一个 LaTex 命令 (如 \\frac 或 \\sqrt) 。 的本地化字符串。
        /// </summary>
        public static string LATEX_COMMAND_EXPECTED {
            get {
                return ResourceManager.GetString("LATEX_COMMAND_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待在 LaTex 命令中的开头的花括号： &quot;\\{&quot;。 的本地化字符串。
        /// </summary>
        public static string LATEX_OPEN_BRACE_EXPECTED {
            get {
                return ResourceManager.GetString("LATEX_OPEN_BRACE_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待 LaTex 命令 &apos;\\left&apos;。 的本地化字符串。
        /// </summary>
        public static string LEFT_COMMAND_EXPECTED {
            get {
                return ResourceManager.GetString("LEFT_COMMAND_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待小于号 &apos;&lt; &apos;。 的本地化字符串。
        /// </summary>
        public static string LESS_THAN_EXPECTED {
            get {
                return ResourceManager.GetString("LESS_THAN_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载中…… 就快出来了！  ^_^ 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定比例 的本地化字符串。
        /// </summary>
        public static string LockRatio {
            get {
                return ResourceManager.GetString("LockRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/Content/Images/funGrapherLogo_zh-CN.png 的本地化字符串。
        /// </summary>
        public static string LogoPath {
            get {
                return ResourceManager.GetString("LogoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;a href=&quot;#&quot; onclick=&quot;return false;&quot; title=&quot;趣涂在线函数画图&quot;&gt;&lt;img src=&quot;{0}&quot; alt=&quot;趣涂 函数作图器！&quot; /&gt;&lt;/a&gt; 的本地化字符串。
        /// </summary>
        public static string LogoRaw {
            get {
                return ResourceManager.GetString("LogoRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待一个负号 &apos;-&apos; 。 的本地化字符串。
        /// </summary>
        public static string NEGATIVE_SIGN_EXPECTED {
            get {
                return ResourceManager.GetString("NEGATIVE_SIGN_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问旧版 的本地化字符串。
        /// </summary>
        public static string OldVersion {
            get {
                return ResourceManager.GetString("OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待一个开始的花括号 &quot;{&quot; 。 的本地化字符串。
        /// </summary>
        public static string OPEN_BRACE_EXPECTED {
            get {
                return ResourceManager.GetString("OPEN_BRACE_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待一个开始的括号 &quot;(&quot; 。 的本地化字符串。
        /// </summary>
        public static string OPEN_PARENTHESIS_EXPECTED {
            get {
                return ResourceManager.GetString("OPEN_PARENTHESIS_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或者 的本地化字符串。
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 趣涂在线函数画图 - 小巧灵活的在线绘图应用，支持不等式与隐函数作图！在线探索各种函数图形。 的本地化字符串。
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待管道符（竖线） &apos;|&apos;。 的本地化字符串。
        /// </summary>
        public static string PIPE_EXPECTED {
            get {
                return ResourceManager.GetString("PIPE_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待一个正号 &apos;+&apos; 。 的本地化字符串。
        /// </summary>
        public static string POSITIVE_SIGN_EXPECTED {
            get {
                return ResourceManager.GetString("POSITIVE_SIGN_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string RefreshGraph {
            get {
                return ResourceManager.GetString("RefreshGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        public static string ResetButtonText {
            get {
                return ResourceManager.GetString("ResetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待 LaTex 命令 &apos;\\right&apos;。 的本地化字符串。
        /// </summary>
        public static string RIGHT_COMMAND_EXPECTED {
            get {
                return ResourceManager.GetString("RIGHT_COMMAND_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存为 BMP 格式的图片... 的本地化字符串。
        /// </summary>
        public static string SaveAsBMP {
            get {
                return ResourceManager.GetString("SaveAsBMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前浏览器不支持创建图片文件，请手动按 Print Screen 键保存图形。 的本地化字符串。
        /// </summary>
        public static string SaveAsImagePlugin_notSupportMessage {
            get {
                return ResourceManager.GetString("SaveAsImagePlugin.notSupportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存为 JPEG 格式的图片... 的本地化字符串。
        /// </summary>
        public static string SaveAsJPEG {
            get {
                return ResourceManager.GetString("SaveAsJPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存为 PNG 格式的图片... 的本地化字符串。
        /// </summary>
        public static string SaveAsPNG {
            get {
                return ResourceManager.GetString("SaveAsPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 t 从  的本地化字符串。
        /// </summary>
        public static string ScaleOfTAxiesTitle {
            get {
                return ResourceManager.GetString("ScaleOfTAxiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 x 从  的本地化字符串。
        /// </summary>
        public static string ScaleOfXAxiesTitle {
            get {
                return ResourceManager.GetString("ScaleOfXAxiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 y 从 的本地化字符串。
        /// </summary>
        public static string ScaleOfYAxiesTitle {
            get {
                return ResourceManager.GetString("ScaleOfYAxiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待一个分号 &quot;;&quot; 。 的本地化字符串。
        /// </summary>
        public static string SEMICOLON_EXPECTED {
            get {
                return ResourceManager.GetString("SEMICOLON_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线函数画图，绘制给定函数的图像。这是一款小巧灵活的在线函数作图工具，多函数支持，而且能够作出隐函数图像！支持 LaTex 表达式，还可以用作在线公式编辑器、图形计算器。在线探索一次函数、二次函数、多项式函数、指数函数、对数函数、三角函数以及各类隐函数图形图像。 的本地化字符串。
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 函数涂鸦板, 涂鸦板, 函数作图, 函数作图器, 作图器, 图形, 在线画图, 在线作图, 在线函数作图器, 2维函数图形, 图形计算器,隐函数作图, 函数图像 的本地化字符串。
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        public static string ShowHelp {
            get {
                return ResourceManager.GetString("ShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图例 的本地化字符串。
        /// </summary>
        public static string ShowLegend {
            get {
                return ResourceManager.GetString("ShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要保存当前图形，您可以直接在图形上“按鼠标右键”，然后选择”另存为……“选项。 的本地化字符串。
        /// </summary>
        public static string TipForSavingGraph {
            get {
                return ResourceManager.GetString("TipForSavingGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;p&gt;自变量或者因变量请用小写 x 或者小写 y 表示。平方用x^2，三次方用x^3，依次类推。多个函数用;号分隔。&lt;/p&gt;
        ///&lt;p&gt;目前只支持&lt;strong style=&quot;color: red;&quot;&gt;显式函数&lt;/strong&gt;，即如下函数是有效的：&lt;/p&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;y = x^2 + 2;&lt;/li&gt;
        ///&lt;li&gt;x = y^3 + 2;&lt;/li&gt;
        ///&lt;li style=&quot;color: red;&quot;&gt;即必须以y = 或者x = 开头，以;号结尾。&lt;/li&gt;
        ///&lt;li style=&quot;color: red;&quot;&gt;若以y = 开头，则等号右边的自变量必须为x；若以x = 开头，则等号右边的自变量必须为y。&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;p&gt;这样的函数（隐函数）是无效的：&lt;/p&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;x + y = 5;&lt;/li&gt;
        ///&lt;li&gt;x^2 + y^2 = 1;&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;p&gt;对于三角函数，应使用如下输入方式（即函数名后跟着&lt;strong style=&quot;color: red;&quot;&gt;小括号&lt;/strong&gt;）：&lt;/p&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;y = sin&lt;span style=&quot;colo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏 控制面板 的本地化字符串。
        /// </summary>
        public static string ToggleNavigationControl {
            get {
                return ResourceManager.GetString("ToggleNavigationControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到 的本地化字符串。
        /// </summary>
        public static string ToTitle {
            get {
                return ResourceManager.GetString("ToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入意外结束。 的本地化字符串。
        /// </summary>
        public static string UNEXPECTED_END_OF_SOURCE {
            get {
                return ResourceManager.GetString("UNEXPECTED_END_OF_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遇到了意外的 LaTex 命令 &apos;\\right&apos;。 的本地化字符串。
        /// </summary>
        public static string UNEXPECTED_RIGHT_COMMAND {
            get {
                return ResourceManager.GetString("UNEXPECTED_RIGHT_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误。 的本地化字符串。
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遇到了不认识的 LaTex 命令。 的本地化字符串。
        /// </summary>
        public static string UNKNOWN_LATEX_COMMAND_MET {
            get {
                return ResourceManager.GetString("UNKNOWN_LATEX_COMMAND_MET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待变量 t 。 的本地化字符串。
        /// </summary>
        public static string VAR_T_EXPECTED {
            get {
                return ResourceManager.GetString("VAR_T_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待变量 x 。 的本地化字符串。
        /// </summary>
        public static string VAR_X_EXPECTED {
            get {
                return ResourceManager.GetString("VAR_X_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待变量 y 。 的本地化字符串。
        /// </summary>
        public static string VAR_Y_EXPECTED {
            get {
                return ResourceManager.GetString("VAR_Y_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期待变量名  (如 abc) 。 的本地化字符串。
        /// </summary>
        public static string VARIABLE_NAME_EXPECTED {
            get {
                return ResourceManager.GetString("VARIABLE_NAME_EXPECTED", resourceCulture);
            }
        }
    }
}
