//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.Plotter.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class plotter_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal plotter_cshtml() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.Plotter.App_LocalResources.plotter.cshtml", typeof(plotter_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This app allows you to plot the scatter of your data easily as well as to work out the stats (mean sample/population standard deviation variance and correlation co-efficient etc.) of your data. Moreover it can find out the linear regression quadratic regression cubic regression and exponential regressions for your data also known as the least square fittings. According to the relation between two variables it finds the linear function quadratic function cubic function and exponential function that best fit  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string about_text1 {
            get {
                return ResourceManager.GetString("about.text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy &amp; Paste:  的本地化字符串。
        /// </summary>
        public static string about_text2 {
            get {
                return ResourceManager.GetString("about.text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can copy and paste data directly from a spreadsheet a tabulated data file or a comma separated values (.csv) file in the box underneath the graph area. Any character that cannot be part of a number - space comma semicolon tabulation... - is considered a column separator. The exponent can be indicated by preceding it by the character E or e for example 5.1E-1 1.78e+3 are valid numbers. Remember data must consist of two columns x and y to get the scatter graph and its regression functions. 的本地化字符串。
        /// </summary>
        public static string about_text3 {
            get {
                return ResourceManager.GetString("about.text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script async src=&quot;http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js&quot;&gt;&lt;/script&gt;
        ///&lt;!-- New version of Fun Grapher --&gt;
        ///&lt;ins class=&quot;adsbygoogle&quot;
        ///     style=&quot;display:inline-block;width:336px;height:280px&quot;
        ///     data-ad-client=&quot;ca-pub-9332882982479681&quot;
        ///     data-ad-slot=&quot;7322914588&quot;&gt;&lt;/ins&gt;
        ///&lt;script&gt;
        ///(adsbygoogle = window.adsbygoogle || []).push({});
        ///&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string AdZone {
            get {
                return ResourceManager.GetString("AdZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script async src=&quot;//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js&quot;&gt;&lt;/script&gt;
        ///&lt;!-- Image Explorer App Ad --&gt;
        ///&lt;ins class=&quot;adsbygoogle&quot;
        ///     style=&quot;display:inline-block;width:300px;height:600px&quot;
        ///     data-ad-client=&quot;ca-pub-9332882982479681&quot;
        ///     data-ad-slot=&quot;9558341781&quot;&gt;&lt;/ins&gt;
        ///&lt;script&gt;
        ///(adsbygoogle = window.adsbygoogle || []).push({});
        ///&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string AdZoneSkyScraper {
            get {
                return ResourceManager.GetString("AdZoneSkyScraper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statistical calculator 的本地化字符串。
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span style=&quot;font-size: small;&quot;&gt;(by &lt;a href=&quot;{0}&quot; title=&quot;ZiZhuJY.com&quot; style=&quot;color: red;&quot;&gt;ZiZhuJY.com&lt;/a&gt;)&lt;/span&gt; 的本地化字符串。
        /// </summary>
        public static string appName_note {
            get {
                return ResourceManager.GetString("appName.note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;h1&gt;Plotter &lt;span style=&quot;font-size: small; color: red; font-weight: normal;&quot;&gt;Online plots, statistics, trends, data fits, estimates and predicts!&lt;/span&gt;&lt;/h1&gt; 的本地化字符串。
        /// </summary>
        public static string BannerTitle {
            get {
                return ResourceManager.GetString("BannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag the chart to pan, and press &apos;shift&apos; + mouse wheel on to the chart to zoom. 的本地化字符串。
        /// </summary>
        public static string ChartInteractiveTip {
            get {
                return ResourceManager.GetString("ChartInteractiveTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span style=&quot;text-decoration: underline;&quot;&gt;C&lt;/span&gt;lear 的本地化字符串。
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Correlation co-efficient with x 的本地化字符串。
        /// </summary>
        public static string correlation_coefficient_with_x {
            get {
                return ResourceManager.GetString("correlation.coefficient.with.x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Correlation co-efficient with y 的本地化字符串。
        /// </summary>
        public static string correlation_coefficient_with_y {
            get {
                return ResourceManager.GetString("correlation.coefficient.with.y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count 的本地化字符串。
        /// </summary>
        public static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cubic Regression 的本地化字符串。
        /// </summary>
        public static string cubic {
            get {
                return ResourceManager.GetString("cubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cubic Fit 的本地化字符串。
        /// </summary>
        public static string cubicFit {
            get {
                return ResourceManager.GetString("cubicFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Estimate/Predict 的本地化字符串。
        /// </summary>
        public static string estimateOrPredict {
            get {
                return ResourceManager.GetString("estimateOrPredict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Estimate/Predict the y value for a specified x value. If the specified x is within the original data&apos;s domain then this process is called estimating; if the specified x exceeds the original data&apos;s domain then this process is called predicting. 的本地化字符串。
        /// </summary>
        public static string estimateOrPredict_text {
            get {
                return ResourceManager.GetString("estimateOrPredict.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exponential Regression 的本地化字符串。
        /// </summary>
        public static string exponential {
            get {
                return ResourceManager.GetString("exponential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exponential Fit 的本地化字符串。
        /// </summary>
        public static string exponentialFit {
            get {
                return ResourceManager.GetString("exponentialFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formula expression 的本地化字符串。
        /// </summary>
        public static string formula_expression {
            get {
                return ResourceManager.GetString("formula.expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Full Screen 的本地化字符串。
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graph 的本地化字符串。
        /// </summary>
        public static string graph {
            get {
                return ResourceManager.GetString("graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input x here:  的本地化字符串。
        /// </summary>
        public static string input_x_here {
            get {
                return ResourceManager.GetString("input.x.here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linear Regression 的本地化字符串。
        /// </summary>
        public static string linear {
            get {
                return ResourceManager.GetString("linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linear Fit 的本地化字符串。
        /// </summary>
        public static string linearFit {
            get {
                return ResourceManager.GetString("linearFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logarithm Regression 的本地化字符串。
        /// </summary>
        public static string logarithm {
            get {
                return ResourceManager.GetString("logarithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logarithm Fit 的本地化字符串。
        /// </summary>
        public static string logarithmFit {
            get {
                return ResourceManager.GetString("logarithmFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mean 的本地化字符串。
        /// </summary>
        public static string mean {
            get {
                return ResourceManager.GetString("mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;h3&gt;Errors encountered:&lt;/h3&gt;&lt;ul&gt;{0}&lt;/ul&gt;&lt;p&gt;Try correct the error and then click the &quot;Plot&quot; button again.&lt;/p&gt;&lt;p&gt;Please ensure that only one data point (i.e. x y pair) on each line and please separte x and y by space comma or semicolon; please not only input x or y in a line and don&apos;t type in special characters.&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p style=&apos;color: black;&apos;&gt;If you are sure that your input is good then please send email to &lt;a href=&apos;mailto:jeff@zizhujy.com?subject=BUG:Ploter&amp;body={1}&apos;&gt;jeff@zizhujy.com&lt;/a&gt; to report  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string message_format {
            get {
                return ResourceManager.GetString("message.format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error encountered when trying to identify &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        public static string message_format_error_encountered_when_identifying {
            get {
                return ResourceManager.GetString("message.format.error.encountered.when.identifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error &apos;{1}&apos; encountered when trying to identify the {0}st data point input &apos;{2}&apos; 的本地化字符串。
        /// </summary>
        public static string message_format_error_encountered_when_identifying_1st_data_point {
            get {
                return ResourceManager.GetString("message.format.error.encountered.when.identifying.1st.data.point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error &apos;{1}&apos; encountered when trying to identify the {0}nd data point input &apos;{2}&apos; 的本地化字符串。
        /// </summary>
        public static string message_format_error_encountered_when_identifying_2nd_data_point {
            get {
                return ResourceManager.GetString("message.format.error.encountered.when.identifying.2nd.data.point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error &apos;{1}&apos; encountered when trying to identify the {0}rd data point input &apos;{2}&apos; 的本地化字符串。
        /// </summary>
        public static string message_format_error_encountered_when_identifying_3rd_data_point {
            get {
                return ResourceManager.GetString("message.format.error.encountered.when.identifying.3rd.data.point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error &apos;{1}&apos; encountered when trying to identify the {0}th data point input &apos;{2}&apos; 的本地化字符串。
        /// </summary>
        public static string message_format_error_encountered_when_identifying_nth_data_point {
            get {
                return ResourceManager.GetString("message.format.error.encountered.when.identifying.nth.data.point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is not a valid data point.A valid data point is an [x, y] data pair. 的本地化字符串。
        /// </summary>
        public static string message_format_not_a_valid_data_point {
            get {
                return ResourceManager.GetString("message.format.not.a.valid.data.point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get the data. Have you input it? 的本地化字符串。
        /// </summary>
        public static string message_no_data {
            get {
                return ResourceManager.GetString("message.no.data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to identify the input because it&apos;s not a valid data point list. The valid data point list should be a list with 2 columns&apos; data. 的本地化字符串。
        /// </summary>
        public static string message_not_a_valid_data_point {
            get {
                return ResourceManager.GetString("message.not.a.valid.data.point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model name 的本地化字符串。
        /// </summary>
        public static string model_name {
            get {
                return ResourceManager.GetString("model.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name of Stats 的本地化字符串。
        /// </summary>
        public static string name_of_stats {
            get {
                return ResourceManager.GetString("name.of.stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 st 的本地化字符串。
        /// </summary>
        public static string ordinal_1st_suffix {
            get {
                return ResourceManager.GetString("ordinal.1st.suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nd 的本地化字符串。
        /// </summary>
        public static string ordinal_2nd_suffix {
            get {
                return ResourceManager.GetString("ordinal.2nd.suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rd 的本地化字符串。
        /// </summary>
        public static string ordinal_3rd_suffix {
            get {
                return ResourceManager.GetString("ordinal.3rd.suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 th 的本地化字符串。
        /// </summary>
        public static string ordinal_nth_suffix {
            get {
                return ResourceManager.GetString("ordinal.nth.suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original data 的本地化字符串。
        /// </summary>
        public static string original_data {
            get {
                return ResourceManager.GetString("original.data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plotter - Online regression/statistics Calculator, basic math statistics, scatter plot, trend fit on the fly! 的本地化字符串。
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters 的本地化字符串。
        /// </summary>
        public static string parameters {
            get {
                return ResourceManager.GetString("parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please pay attention! 的本地化字符串。
        /// </summary>
        public static string please_pay_attention {
            get {
                return ResourceManager.GetString("please.pay.attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span style=&quot;text-decoration: underline;&quot;&gt;P&lt;/span&gt;lot 的本地化字符串。
        /// </summary>
        public static string plot {
            get {
                return ResourceManager.GetString("plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polynomial 的本地化字符串。
        /// </summary>
        public static string polynomial_model_name_post {
            get {
                return ResourceManager.GetString("polynomial.model.name.post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string polynomial_model_name_pre {
            get {
                return ResourceManager.GetString("polynomial.model.name.pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 th Polynomial Fit 的本地化字符串。
        /// </summary>
        public static string polynomialFit_post {
            get {
                return ResourceManager.GetString("polynomialFit.post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string polynomialFit_pre {
            get {
                return ResourceManager.GetString("polynomialFit.pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Population standard deviation 的本地化字符串。
        /// </summary>
        public static string population_standard_deviation {
            get {
                return ResourceManager.GetString("population.standard.deviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Population variance 的本地化字符串。
        /// </summary>
        public static string population_variance {
            get {
                return ResourceManager.GetString("population.variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quadratic Regression 的本地化字符串。
        /// </summary>
        public static string quadratic {
            get {
                return ResourceManager.GetString("quadratic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quadratic Fit 的本地化字符串。
        /// </summary>
        public static string quadraticFit {
            get {
                return ResourceManager.GetString("quadraticFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sample standard deviation 的本地化字符串。
        /// </summary>
        public static string sample_standard_deviation {
            get {
                return ResourceManager.GetString("sample.standard.deviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sample variance 的本地化字符串。
        /// </summary>
        public static string sample_variance {
            get {
                return ResourceManager.GetString("sample.variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as BMP...  的本地化字符串。
        /// </summary>
        public static string SaveAsBMP {
            get {
                return ResourceManager.GetString("SaveAsBMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, this browser is not capable of creating image files, please use PRINT SCREEN key instead! 的本地化字符串。
        /// </summary>
        public static string SaveAsImagePlugin_notSupportMessage {
            get {
                return ResourceManager.GetString("SaveAsImagePlugin.notSupportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as JPEG... 的本地化字符串。
        /// </summary>
        public static string SaveAsJPEG {
            get {
                return ResourceManager.GetString("SaveAsJPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as PNG... 的本地化字符串。
        /// </summary>
        public static string SaveAsPNG {
            get {
                return ResourceManager.GetString("SaveAsPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ploter - online regression calculator. Scatter plot, statistical calculation, linear fit, quadratic fit,cubic fit on the fly! 的本地化字符串。
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ploter, scatter, statistical calculation, trend, fit, linear, quadratic, cubic, regression 的本地化字符串。
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Square sum of fitting errors 的本地化字符串。
        /// </summary>
        public static string square_sum_of_fitting_errors {
            get {
                return ResourceManager.GetString("square.sum.of.fitting.errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stats 的本地化字符串。
        /// </summary>
        public static string stats {
            get {
                return ResourceManager.GetString("stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stats for x 的本地化字符串。
        /// </summary>
        public static string stats_for_x {
            get {
                return ResourceManager.GetString("stats.for.x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stats for y 的本地化字符串。
        /// </summary>
        public static string stats_for_y {
            get {
                return ResourceManager.GetString("stats.for.y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum 的本地化字符串。
        /// </summary>
        public static string sum {
            get {
                return ResourceManager.GetString("sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum of product 的本地化字符串。
        /// </summary>
        public static string sum_of_product {
            get {
                return ResourceManager.GetString("sum.of.product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum of squares 的本地化字符串。
        /// </summary>
        public static string sum_of_squares {
            get {
                return ResourceManager.GetString("sum.of.squares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To save current graph, you can directly &quot;mouse right click&quot; on the graph, then choose &quot;Save image as...&quot; option.  的本地化字符串。
        /// </summary>
        public static string TipForSavingGraph {
            get {
                return ResourceManager.GetString("TipForSavingGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle navigation control 的本地化字符串。
        /// </summary>
        public static string ToggleNavigationControl {
            get {
                return ResourceManager.GetString("ToggleNavigationControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
    }
}
