//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Html5AppLayout_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Html5AppLayout_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.Shared.App_LocalResources._Html5AppLayout.cshtml", typeof(_Html5AppLayout_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;&lt;!--
        ///google_ad_client = &quot;ca-pub-9332882982479681&quot;;
        ////* 统计计算器底栏广告 */
        ///google_ad_slot = &quot;3513464186&quot;;
        ///google_ad_width = 468;
        ///google_ad_height = 60;
        /////--&gt;
        ///&lt;/script&gt;
        ///&lt;script type=&quot;text/javascript&quot;
        ///src=&quot;http://pagead2.googlesyndication.com/pagead/show_ads.js&quot;&gt;
        ///&lt;/script&gt;.
        /// </summary>
        public static string AdCode_Bottom {
            get {
                return ResourceManager.GetString("AdCode_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:jeff@zizhujy.com.
        /// </summary>
        public static string FooterMenuContactMeLink {
            get {
                return ResourceManager.GetString("FooterMenuContactMeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系我.
        /// </summary>
        public static string FooterMenuContactMeText {
            get {
                return ResourceManager.GetString("FooterMenuContactMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系我.
        /// </summary>
        public static string FooterMenuContactMeTitle {
            get {
                return ResourceManager.GetString("FooterMenuContactMeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编程，数学.
        /// </summary>
        public static string LogoTextDescRaw {
            get {
                return ResourceManager.GetString("LogoTextDescRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 紫竹叽歪.
        /// </summary>
        public static string LogoTitleText {
            get {
                return ResourceManager.GetString("LogoTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 紫竹叽歪.
        /// </summary>
        public static string LogoTitleTitle {
            get {
                return ResourceManager.GetString("LogoTitleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string MenuAboutText {
            get {
                return ResourceManager.GetString("MenuAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于我.
        /// </summary>
        public static string MenuAboutTitle {
            get {
                return ResourceManager.GetString("MenuAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用工厂.
        /// </summary>
        public static string MenuApplicationFactoryText {
            get {
                return ResourceManager.GetString("MenuApplicationFactoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线应用工厂.
        /// </summary>
        public static string MenuApplicationFactoryTitle {
            get {
                return ResourceManager.GetString("MenuApplicationFactoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 博客.
        /// </summary>
        public static string MenuBlogText {
            get {
                return ResourceManager.GetString("MenuBlogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的博客.
        /// </summary>
        public static string MenuBlogTitle {
            get {
                return ResourceManager.GetString("MenuBlogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 函数画图.
        /// </summary>
        public static string MenuHomeText {
            get {
                return ResourceManager.GetString("MenuHomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线函数画图 - 图形计算器，在线求解方程.
        /// </summary>
        public static string MenuHomeTitle {
            get {
                return ResourceManager.GetString("MenuHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 矩阵计算器.
        /// </summary>
        public static string MenuMatrixText {
            get {
                return ResourceManager.GetString("MenuMatrixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线矩阵计算器.
        /// </summary>
        public static string MenuMatrixTitle {
            get {
                return ResourceManager.GetString("MenuMatrixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计计算器.
        /// </summary>
        public static string MenuPloterText {
            get {
                return ResourceManager.GetString("MenuPloterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线统计计算器 - 作散点图，趋势拟合，线性回归.
        /// </summary>
        public static string MenuPloterTitle {
            get {
                return ResourceManager.GetString("MenuPloterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Google Tracking Code --&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///    &lt;!--
        ///        var _gaq = _gaq || [];
        ///        _gaq.push([&apos;_setAccount&apos;, &apos;UA-4867336-2&apos;]);
        ///        _gaq.push([&apos;_setDomainName&apos;, &apos;.zizhujy.com&apos;]);
        ///        _gaq.push([&apos;_trackPageview&apos;]);
        ///
        ///        (function () {
        ///            var ga = document.createElement(&apos;script&apos;); ga.type = &apos;text/javascript&apos;; ga.async = true;
        ///            ga.src = (&apos;https:&apos; == document.location.protocol ? &apos;https://&apos; : &apos;http://&apos;) + &apos;stats.g.doubleclick.net/dc.js&apos;;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TrackingCode {
            get {
                return ResourceManager.GetString("TrackingCode", resourceCulture);
            }
        }
    }
}
