//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layout_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout_cshtml() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.Shared.App_LocalResources._Layout.cshtml", typeof(_Layout_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script type=&quot;text/javascript&quot;&gt;&lt;!--
        ///google_ad_client = &quot;ca-pub-9332882982479681&quot;;
        ////* zizhujy Ad Banner */
        ///google_ad_slot = &quot;7545401320&quot;;
        ///google_ad_width = 468;
        ///google_ad_height = 15;
        /////--&gt;
        ///&lt;/script&gt;
        ///&lt;script type=&quot;text/javascript&quot;
        ///src=&quot;http://pagead2.googlesyndication.com/pagead/show_ads.js&quot;&gt;
        ///&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string AdBannerLink {
            get {
                return ResourceManager.GetString("AdBannerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string MenuLinkAbout {
            get {
                return ResourceManager.GetString("MenuLinkAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Factory 的本地化字符串。
        /// </summary>
        public static string MenuLinkApplicationFactory {
            get {
                return ResourceManager.GetString("MenuLinkApplicationFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blog 的本地化字符串。
        /// </summary>
        public static string MenuLinkBlog {
            get {
                return ResourceManager.GetString("MenuLinkBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function Grapher 的本地化字符串。
        /// </summary>
        public static string MenuLinkFunctionGraffti {
            get {
                return ResourceManager.GetString("MenuLinkFunctionGraffti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string MenuLinkHome {
            get {
                return ResourceManager.GetString("MenuLinkHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matrix Calculator 的本地化字符串。
        /// </summary>
        public static string MenuLinkMatrix {
            get {
                return ResourceManager.GetString("MenuLinkMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ploter 的本地化字符串。
        /// </summary>
        public static string MenuLinkPloter {
            get {
                return ResourceManager.GetString("MenuLinkPloter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool Box 的本地化字符串。
        /// </summary>
        public static string MenuLinkToolBox {
            get {
                return ResourceManager.GetString("MenuLinkToolBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script&gt;
        ///  (function(i,s,o,g,r,a,m){i[&apos;GoogleAnalyticsObject&apos;]=r;i[r]=i[r]||function(){
        ///  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        ///  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        ///  })(window,document,&apos;script&apos;,&apos;//www.google-analytics.com/analytics.js&apos;,&apos;ga&apos;);
        ///
        ///  ga(&apos;create&apos;, &apos;UA-4867336-3&apos;, &apos;zizhujy.com&apos;);
        ///  ga(&apos;send&apos;, &apos;pageview&apos;);
        ///
        ///&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string TrackingCode {
            get {
                return ResourceManager.GetString("TrackingCode", resourceCulture);
            }
        }
    }
}
