//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.JsLibs.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class navigationControl_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal navigationControl_cshtml() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.JsLibs.App_LocalResources.navigationControl.cshtml", typeof(navigationControl_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 基本用法 的本地化字符串。
        /// </summary>
        public static string BasicExample {
            get {
                return ResourceManager.GetString("BasicExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线示例： 的本地化字符串。
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/Jeff-Tian/jquery.flot.navigationControl 的本地化字符串。
        /// </summary>
        public static string ForkMeOnGitHubUrl {
            get {
                return ResourceManager.GetString("ForkMeOnGitHubUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同一页面多个图形的场景 的本地化字符串。
        /// </summary>
        public static string MultipleChartsExample {
            get {
                return ResourceManager.GetString("MultipleChartsExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为 Flot 图形库打造的控制盘。 的本地化字符串。
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://raw.githubusercontent.com/Jeff-Tian/jquery.flot.navigationControl/master/README.md 的本地化字符串。
        /// </summary>
        public static string README_URI {
            get {
                return ResourceManager.GetString("README_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是一个 Flot 插件，它能够在 Flot 图形上显示一个控制盘，从而方便用户对图形进行上下左右移动、大小缩放的操作。这个对于触摸屏的用户尤其有用。 的本地化字符串。
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 flot, 插件, 控制盘 的本地化字符串。
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://raw.githubusercontent.com/Jeff-Tian/jquery.flot.navigationControl/master 的本地化字符串。
        /// </summary>
        public static string UrlBase {
            get {
                return ResourceManager.GetString("UrlBase", resourceCulture);
            }
        }
    }
}
