//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.GeekCalculator.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class index_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal index_cshtml() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.GeekCalculator.App_LocalResources.index.cshtml", typeof(index_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script async src=&quot;http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js&quot;&gt;&lt;/script&gt;
        ///&lt;!-- New version of Fun Grapher --&gt;
        ///&lt;ins class=&quot;adsbygoogle&quot;
        ///     style=&quot;display:inline-block;width:336px;height:280px&quot;
        ///     data-ad-client=&quot;ca-pub-9332882982479681&quot;
        ///     data-ad-slot=&quot;7322914588&quot;&gt;&lt;/ins&gt;
        ///&lt;script&gt;
        ///(adsbygoogle = window.adsbygoogle || []).push({});
        ///&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string AdZone {
            get {
                return ResourceManager.GetString("AdZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本示例 的本地化字符串。
        /// </summary>
        public static string BasicExample {
            get {
                return ResourceManager.GetString("BasicExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除算式 的本地化字符串。
        /// </summary>
        public static string ClearExpressions {
            get {
                return ResourceManager.GetString("ClearExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小数分数互换 的本地化字符串。
        /// </summary>
        public static string DecimalFractionConvertion {
            get {
                return ResourceManager.GetString("DecimalFractionConvertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小数与分数快速转换；将无限循环小数转换为分数表示。 的本地化字符串。
        /// </summary>
        public static string DecimalFractionConvertionDescription {
            get {
                return ResourceManager.GetString("DecimalFractionConvertionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将小数转换成它的分数形式，你甚至可以将一个无限循环小数转换成它的精确分数表示！ 想知道这是怎么做到的？这篇博文有详细的算法描述：《&lt;strong&gt;&lt;a href=&quot;http://zizhujy.com/blog/post/2014/01/21/%E5%B0%86%E5%B0%8F%E6%95%B0%E8%BD%AC%E5%8C%96%E4%B8%BA%E5%88%86%E6%95%B0%E7%9A%84%E7%AE%97%E6%B3%95.aspx&quot; target=&quot;_blank&quot;&gt;将小数转化为分数的算法&lt;/a&gt;&lt;/strong&gt;》。 的本地化字符串。
        /// </summary>
        public static string DecimalFractionConvertionLinkText {
            get {
                return ResourceManager.GetString("DecimalFractionConvertionLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将小数转换为分数表示 的本地化字符串。
        /// </summary>
        public static string DecimalFractionConvertionLinkTitle {
            get {
                return ResourceManager.GetString("DecimalFractionConvertionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 示例： 的本地化字符串。
        /// </summary>
        public static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 极速： 的本地化字符串。
        /// </summary>
        public static string Fast {
            get {
                return ResourceManager.GetString("Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 即时响应，就在你输入的时候显示结果。如果你不小心输入了不正确的算式，它会立即提示输入的错误信息以帮助你更正； 的本地化字符串。
        /// </summary>
        public static string FastDescription {
            get {
                return ResourceManager.GetString("FastDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特性： 的本地化字符串。
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自由： 的本地化字符串。
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你只用专注于输入数学算式，而结果自动在旁边呈现； 的本地化字符串。
        /// </summary>
        public static string FreeDescription {
            get {
                return ResourceManager.GetString("FreeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 极客计算器 的本地化字符串。
        /// </summary>
        public static string GeekCalculator {
            get {
                return ResourceManager.GetString("GeekCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取包含当前算式的永久链接。 的本地化字符串。
        /// </summary>
        public static string GetLinkMessageTitle {
            get {
                return ResourceManager.GetString("GetLinkMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取链接 的本地化字符串。
        /// </summary>
        public static string GetLinkTitle {
            get {
                return ResourceManager.GetString("GetLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无限大量 的本地化字符串。
        /// </summary>
        public static string Infinite {
            get {
                return ResourceManager.GetString("Infinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分母是符号0的分数，称为无限大量。在这个以符号0作为分母的量中，可以加入或取出任何量而无任何变化发生，就像在毁灭世界或创造世界的时期，那个无穷的、不变的上帝没有发生任何变化一样，虽然有大量种类的生物被吞没或产生出来。 的本地化字符串。
        /// </summary>
        public static string InfiniteIntro {
            get {
                return ResourceManager.GetString("InfiniteIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ——— 【英】斯科特 《数学史》 的本地化字符串。
        /// </summary>
        public static string MathHistory {
            get {
                return ResourceManager.GetString("MathHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一款牛屄的急速的科学计算器。在你输入数学计算式的同时在旁边即时显示计算结果，让极客们爱不释手。 的本地化字符串。
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算器, 科学, 极客 的本地化字符串。
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 极客计算器 -- 牛屄的科学计算器，快速无与伦比！ 的本地化字符串。
        /// </summary>
        public static string SeoTitle {
            get {
                return ResourceManager.GetString("SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分享： 的本地化字符串。
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击“获取链接”，随时将你的计算过程保存下来或者分享出去。 的本地化字符串。
        /// </summary>
        public static string ShareDescription {
            get {
                return ResourceManager.GetString("ShareDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过程 的本地化字符串。
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可以一行一行地将算式列出来，方便地用于展示你的解题过程； 的本地化字符串。
        /// </summary>
        public static string StepDescription {
            get {
                return ResourceManager.GetString("StepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 教程： 的本地化字符串。
        /// </summary>
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还没来得及写。不过，它的使用真的非常简单，你可以通过查看示例学会。然后，你可以将你的经验发布在你的博客上，或者将你的计算过程的链接粘贴在你的微博上，大家可以通过你的实际使用获得启发。 的本地化字符串。
        /// </summary>
        public static string TutorialDescription {
            get {
                return ResourceManager.GetString("TutorialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个小小的改变将会大大不同，你选择什么样的改变呢？ 的本地化字符串。
        /// </summary>
        public static string YouChooseLinkText {
            get {
                return ResourceManager.GetString("YouChooseLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你选择哪个？ 的本地化字符串。
        /// </summary>
        public static string YouChooseLinkTitle {
            get {
                return ResourceManager.GetString("YouChooseLinkTitle", resourceCulture);
            }
        }
    }
}
