//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Application {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Application() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.App_GlobalResources.Application", typeof(Application).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Hire me! 的本地化字符串。
        /// </summary>
        public static string FooterMenuHireMeLink {
            get {
                return ResourceManager.GetString("FooterMenuHireMeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get the PDF version of this url: &apos;{0}&apos;.\r\n{1} 的本地化字符串。
        /// </summary>
        public static string Format_FailedToGetPDF {
            get {
                return ResourceManager.GetString("Format_FailedToGetPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Function Grapher 的本地化字符串。
        /// </summary>
        public static string FunctionGrapher {
            get {
                return ResourceManager.GetString("FunctionGrapher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plot and graph equations online!. This is an easy to use Online Function Grapher, supporting multiple functions and even implict functions plotting &amp;amp; graphing!  And supporting LaTex expression, can be used as an online equation editor or graphing calculator as well. Explore all kinds of functions&amp;#39; graphs online. 的本地化字符串。
        /// </summary>
        public static string FunctionGrapherIntro {
            get {
                return ResourceManager.GetString("FunctionGrapherIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Geek Calculator 的本地化字符串。
        /// </summary>
        public static string GeekCalculator {
            get {
                return ResourceManager.GetString("GeekCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A fast awesome scientific calculator. Type mathematical expressions and the answer just shows immediately next to your expressions, which makes geeks love it so much. 的本地化字符串。
        /// </summary>
        public static string GeekCalculatorIntro {
            get {
                return ResourceManager.GetString("GeekCalculatorIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graph World 的本地化字符串。
        /// </summary>
        public static string GraphWorld {
            get {
                return ResourceManager.GetString("GraphWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate/draw complete, regular, and random graphs, etc, online. 的本地化字符串。
        /// </summary>
        public static string GraphWorldIntro {
            get {
                return ResourceManager.GetString("GraphWorldIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matrix Calculator 的本地化字符串。
        /// </summary>
        public static string MatrixCalculator {
            get {
                return ResourceManager.GetString("MatrixCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matrix calculation - Inverse, Transpose, Add, Subtract, Multiply Matrices online! 的本地化字符串。
        /// </summary>
        public static string MatrixCalculatorIntro {
            get {
                return ResourceManager.GetString("MatrixCalculatorIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://zizhujy.apphb.com 的本地化字符串。
        /// </summary>
        public static string MirrorSiteLink {
            get {
                return ResourceManager.GetString("MirrorSiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mirror Site 的本地化字符串。
        /// </summary>
        public static string MirrorSiteText {
            get {
                return ResourceManager.GetString("MirrorSiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mirror Site 的本地化字符串。
        /// </summary>
        public static string MirrorSiteTitle {
            get {
                return ResourceManager.GetString("MirrorSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zi Zhu Home 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF Converter 的本地化字符串。
        /// </summary>
        public static string PDFConverter {
            get {
                return ResourceManager.GetString("PDFConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert web pages to PDF on the fly! 的本地化字符串。
        /// </summary>
        public static string PDFConverterIntro {
            get {
                return ResourceManager.GetString("PDFConverterIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plotter - Online Regression/Statistical Calculator 的本地化字符串。
        /// </summary>
        public static string Plotter {
            get {
                return ResourceManager.GetString("Plotter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online plots, regression calculator, statistics, trends, data fits, estimates and predicts! 的本地化字符串。
        /// </summary>
        public static string PlotterIntro {
            get {
                return ResourceManager.GetString("PlotterIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script&gt;
        ///  (function(i,s,o,g,r,a,m){i[&apos;GoogleAnalyticsObject&apos;]=r;i[r]=i[r]||function(){
        ///  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        ///  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        ///  })(window,document,&apos;script&apos;,&apos;//www.google-analytics.com/analytics.js&apos;,&apos;ga&apos;);
        ///
        ///  ga(&apos;create&apos;, &apos;UA-4867336-3&apos;, &apos;zizhujy.com&apos;);
        ///  ga(&apos;send&apos;, &apos;pageview&apos;);
        ///
        ///&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string SiteTrackingCode {
            get {
                return ResourceManager.GetString("SiteTrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   的本地化字符串。
        /// </summary>
        public static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZiZhu JY 的本地化字符串。
        /// </summary>
        public static string ZiZhuJY {
            get {
                return ResourceManager.GetString("ZiZhuJY", resourceCulture);
            }
        }
    }
}
