//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Application {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Application() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.App_GlobalResources.Application", typeof(Application).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire me!.
        /// </summary>
        public static string FooterMenuHireMeLink {
            get {
                return ResourceManager.GetString("FooterMenuHireMeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the PDF version of this url: &apos;{0}&apos;.\r\n{1}.
        /// </summary>
        public static string Format_FailedToGetPDF {
            get {
                return ResourceManager.GetString("Format_FailedToGetPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Function Grapher.
        /// </summary>
        public static string FunctionGrapher {
            get {
                return ResourceManager.GetString("FunctionGrapher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot and graph equations online!. This is an easy to use Online Function Grapher, supporting multiple functions and even implict functions plotting &amp;amp; graphing!  And supporting LaTex expression, can be used as an online equation editor or graphing calculator as well. Explore all kinds of functions&amp;#39; graphs online..
        /// </summary>
        public static string FunctionGrapherIntro {
            get {
                return ResourceManager.GetString("FunctionGrapherIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geek Calculator.
        /// </summary>
        public static string GeekCalculator {
            get {
                return ResourceManager.GetString("GeekCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fast awesome scientific calculator. Type mathematical expressions and the answer just shows immediately next to your expressions, which makes geeks love it so much..
        /// </summary>
        public static string GeekCalculatorIntro {
            get {
                return ResourceManager.GetString("GeekCalculatorIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph World.
        /// </summary>
        public static string GraphWorld {
            get {
                return ResourceManager.GetString("GraphWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate/draw complete, regular, and random graphs, etc, online..
        /// </summary>
        public static string GraphWorldIntro {
            get {
                return ResourceManager.GetString("GraphWorldIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix Calculator.
        /// </summary>
        public static string MatrixCalculator {
            get {
                return ResourceManager.GetString("MatrixCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix calculation - Inverse, Transpose, Add, Subtract, Multiply Matrices online!.
        /// </summary>
        public static string MatrixCalculatorIntro {
            get {
                return ResourceManager.GetString("MatrixCalculatorIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://zizhujy.apphb.com.
        /// </summary>
        public static string MirrorSiteLink {
            get {
                return ResourceManager.GetString("MirrorSiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Site.
        /// </summary>
        public static string MirrorSiteText {
            get {
                return ResourceManager.GetString("MirrorSiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Site.
        /// </summary>
        public static string MirrorSiteTitle {
            get {
                return ResourceManager.GetString("MirrorSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zi Zhu Home.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Converter.
        /// </summary>
        public static string PDFConverter {
            get {
                return ResourceManager.GetString("PDFConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert web pages to PDF on the fly!.
        /// </summary>
        public static string PDFConverterIntro {
            get {
                return ResourceManager.GetString("PDFConverterIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plotter - Online Regression/Statistical Calculator.
        /// </summary>
        public static string Plotter {
            get {
                return ResourceManager.GetString("Plotter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online plots, regression calculator, statistics, trends, data fits, estimates and predicts!.
        /// </summary>
        public static string PlotterIntro {
            get {
                return ResourceManager.GetString("PlotterIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;
        ///  (function(i,s,o,g,r,a,m){i[&apos;GoogleAnalyticsObject&apos;]=r;i[r]=i[r]||function(){
        ///  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        ///  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        ///  })(window,document,&apos;script&apos;,&apos;//www.google-analytics.com/analytics.js&apos;,&apos;ga&apos;);
        ///
        ///  ga(&apos;create&apos;, &apos;UA-4867336-3&apos;, &apos;zizhujy.com&apos;);
        ///  ga(&apos;send&apos;, &apos;pageview&apos;);
        ///
        ///&lt;/script&gt;.
        /// </summary>
        public static string SiteTrackingCode {
            get {
                return ResourceManager.GetString("SiteTrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZiZhu JY.
        /// </summary>
        public static string ZiZhuJY {
            get {
                return ResourceManager.GetString("ZiZhuJY", resourceCulture);
            }
        }
    }
}
