//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.Home.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class horseYear_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal horseYear_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.Home.App_LocalResources.horseYear.cshtml", typeof(horseYear_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者：.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 王小川.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜狗公司 CEO 王小川.
        /// </summary>
        public static string AuthorTitle {
            get {
                return ResourceManager.GetString("AuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  —— 马年！.
        /// </summary>
        public static string BannerTitle {
            get {
                return ResourceManager.GetString("BannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在计算…….
        /// </summary>
        public static string Drawing {
            get {
                return ResourceManager.GetString("Drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项.
        /// </summary>
        public static string FlotOptionButtonTitle {
            get {
                return ResourceManager.GetString("FlotOptionButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图例.
        /// </summary>
        public static string FlotOptionsPopUp_ShowLegend {
            get {
                return ResourceManager.GetString("FlotOptionsPopUp_ShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项.
        /// </summary>
        public static string FlotOptionsPopUpTitle {
            get {
                return ResourceManager.GetString("FlotOptionsPopUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全屏.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 函数涂鸦艺术作品： .
        /// </summary>
        public static string FunGrapherArt {
            get {
                return ResourceManager.GetString("FunGrapherArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小马过河.
        /// </summary>
        public static string FunGrapherArtName {
            get {
                return ResourceManager.GetString("FunGrapherArtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载…….
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 紫竹叽歪年轮 —— 认识中国生肖（并欣赏函数涂鸦艺术）.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存为 BMP 格式的图像…….
        /// </summary>
        public static string SaveAsBMP {
            get {
                return ResourceManager.GetString("SaveAsBMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存为 JPEG 格式的图像…….
        /// </summary>
        public static string SaveAsJPEG {
            get {
                return ResourceManager.GetString("SaveAsJPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存为 PNG 格式的图像…….
        /// </summary>
        public static string SaveAsPNG {
            get {
                return ResourceManager.GetString("SaveAsPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 认识中国生肖。通过函数图像艺术来了解中国生肖，并且享受关于它们的美文。.
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 紫竹叽歪,年轮,中国生肖,生肖, 函数, 函数涂鸦艺术.
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存图像…….
        /// </summary>
        public static string TipForSavingGraph {
            get {
                return ResourceManager.GetString("TipForSavingGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示/隐藏 导航按钮.
        /// </summary>
        public static string ToggleNavigationControl {
            get {
                return ResourceManager.GetString("ToggleNavigationControl", resourceCulture);
            }
        }
    }
}
