//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.Home.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class index_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal index_cshtml() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.Home.App_LocalResources.index.cshtml", typeof(index_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Blog feeds: 的本地化字符串。
        /// </summary>
        public static string BlogFeeds {
            get {
                return ResourceManager.GetString("BlogFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact Info: 的本地化字符串。
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Story  的本地化字符串。
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Tools 的本地化字符串。
        /// </summary>
        public static string OnlineTools {
            get {
                return ResourceManager.GetString("OnlineTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online tools made by Jeff Tian. Function graphing tool, plotter, regression/statistical calculater, geek calculator, matrix calculator, html to pdf converter, graph generator, and more. 的本地化字符串。
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online tools, Function graphing tool, plotter, statistical calculater, geek calculator, matrix calculator, html to pdf converter, graph generator, regression calculator 的本地化字符串。
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Facebook: 的本地化字符串。
        /// </summary>
        public static string SocialLinks_Label_Facebook {
            get {
                return ResourceManager.GetString("SocialLinks.Label.Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github: 的本地化字符串。
        /// </summary>
        public static string SocialLinks_Label_Github {
            get {
                return ResourceManager.GetString("SocialLinks.Label.Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ: 的本地化字符串。
        /// </summary>
        public static string SocialLinks_Label_QQ {
            get {
                return ResourceManager.GetString("SocialLinks.Label.QQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Renren: 的本地化字符串。
        /// </summary>
        public static string SocialLinks_Label_Renren {
            get {
                return ResourceManager.GetString("SocialLinks.Label.Renren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sina Weibo:  的本地化字符串。
        /// </summary>
        public static string SocialLinks_Label_Weibo {
            get {
                return ResourceManager.GetString("SocialLinks.Label.Weibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jeff Tian 的本地化字符串。
        /// </summary>
        public static string SocialLinks_Title_Facebook {
            get {
                return ResourceManager.GetString("SocialLinks.Title.Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jeff-Tian 的本地化字符串。
        /// </summary>
        public static string SocialLinks_Title_Github {
            get {
                return ResourceManager.GetString("SocialLinks.Title.Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jeff Tian 的本地化字符串。
        /// </summary>
        public static string SoialLinks_Title_Renren {
            get {
                return ResourceManager.GetString("SoialLinks.Title.Renren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I started working as a programmer in 2011 at a company located in ZiZhu Scientific Park, Shanghai. To memorize this event I opened this web site and name it &quot;ZiZhuJY&quot;. &quot;JY&quot; means I want to make some noise to this world through this web site platform.
        ///
        ///I had been teaching myself mathematics, so I made several online math tools. For example, &quot;Online Function Grapher&quot;, &quot;Plotter/Online statistical calculator&quot;, &quot;Online Geek Calculator&quot;, &quot;Online Matrix Calculator&quot;, etc. I can&apos;t live without them, especially in  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Story {
            get {
                return ResourceManager.GetString("Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zi Zhu JY - A lot of online tools made by Jeff Tian. 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
