//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.Home.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resume_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resume_cshtml() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.Home.App_LocalResources.Resume.cshtml", typeof(Resume_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Resume of Jeff Tian 的本地化字符串。
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF 的本地化字符串。
        /// </summary>
        public static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;h2&gt;Resume&lt;/h2&gt;
        ///&lt;hr style=&quot;background-color: #cccccc; height: 1px;&quot; /&gt;
        ///&lt;div id=&quot;bio&quot; class=&quot;section&quot;&gt;
        ///    &lt;h3&gt;Bio&lt;/h3&gt;
        ///    &lt;div style=&quot;float: left; margin-right: 1em;&quot;&gt;
        ///        &lt;img src=&quot;../../Content/Images/JeffTian.jpg&quot; style=&quot;width: 140px;&quot; /&gt;
        ///    &lt;/div&gt;
        ///    &lt;p&gt;Jeff Tian, Bachelor degree, has been working for 7 years. With great passion on programming, high pursuit of product quality, is now working as a senior developer at a CRM system team. He enjoys learning skills and is good at applying what  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string RESUME_Content {
            get {
                return ResourceManager.GetString("RESUME_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://raw.githubusercontent.com/Jeff-Tian/Resume/master/resume.css 的本地化字符串。
        /// </summary>
        public static string RESUME_CSS_URI {
            get {
                return ResourceManager.GetString("RESUME_CSS_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://raw.githubusercontent.com/Jeff-Tian/Resume/master/en-US.md 的本地化字符串。
        /// </summary>
        public static string RESUME_URI {
            get {
                return ResourceManager.GetString("RESUME_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume of Jeff Tian.pdf 的本地化字符串。
        /// </summary>
        public static string ResumePDFFileName {
            get {
                return ResourceManager.GetString("ResumePDFFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume of Devlepor Jeff Tian 的本地化字符串。
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume, Jeff, Tian, developer 的本地化字符串。
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
    }
}
