//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMarkupMin.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebMarkupMin.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not specified a name of assembly..
        /// </summary>
        public static string Common_AssemblyNameIsEmpty {
            get {
                return ResourceManager.GetString("Common_AssemblyNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not convert value &apos;{0}&apos; of enumeration type &apos;{1}&apos; to value of enumeration type &apos;{2}&apos;..
        /// </summary>
        public static string Common_EnumValueConversionFailed {
            get {
                return ResourceManager.GetString("Common_EnumValueConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During instantiate an object of type &apos;{0}&apos; from assembly &apos;{1}&apos; error occurred..
        /// </summary>
        public static string Common_InstanceCreationFailed {
            get {
                return ResourceManager.GetString("Common_InstanceCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not specified a type name..
        /// </summary>
        public static string Common_TypeNameIsEmpty {
            get {
                return ResourceManager.GetString("Common_TypeNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty..
        /// </summary>
        public static string Common_ValueIsEmpty {
            get {
                return ResourceManager.GetString("Common_ValueIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        public static string Common_ValueIsNull {
            get {
                return ResourceManager.GetString("Common_ValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-minifier with name &apos;{1}&apos; is not registered in configuration file..
        /// </summary>
        public static string Configuration_CodeMinifierNotRegistered {
            get {
                return ResourceManager.GetString("Configuration_CodeMinifierNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default {0}-minifier not specified..
        /// </summary>
        public static string Configuration_DefaultCodeMinifierNotSpecified {
            get {
                return ResourceManager.GetString("Configuration_DefaultCodeMinifierNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default logger not specified..
        /// </summary>
        public static string Configuration_DefaultLoggerNotSpecified {
            get {
                return ResourceManager.GetString("Configuration_DefaultLoggerNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger with name &apos;{0}&apos; is not registered in configuration file..
        /// </summary>
        public static string Configuration_LoggerNotRegistered {
            get {
                return ResourceManager.GetString("Configuration_LoggerNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading of {0} minifier settings from the configuration file is prohibited..
        /// </summary>
        public static string Configuration_ReloadingCodeMinifierSettingsProhibited {
            get {
                return ResourceManager.GetString("Configuration_ReloadingCodeMinifierSettingsProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ErrorDetails_Category {
            get {
                return ResourceManager.GetString("ErrorDetails_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column number.
        /// </summary>
        public static string ErrorDetails_ColumnNumber {
            get {
                return ResourceManager.GetString("ErrorDetails_ColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ErrorDetails_File {
            get {
                return ResourceManager.GetString("ErrorDetails_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number.
        /// </summary>
        public static string ErrorDetails_LineNumber {
            get {
                return ResourceManager.GetString("ErrorDetails_LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ErrorDetails_Message {
            get {
                return ResourceManager.GetString("ErrorDetails_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source fragment.
        /// </summary>
        public static string ErrorDetails_SourceFragment {
            get {
                return ResourceManager.GetString("ErrorDetails_SourceFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During minification of {0} binding expression error has occurred: {1}..
        /// </summary>
        public static string ErrorMessage_BindingExpressionMinificationFailed {
            get {
                return ResourceManager.GetString("ErrorMessage_BindingExpressionMinificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is impossible to parse a &quot;End If conditional comment&quot;, because not declared &quot;If conditional comment&quot;..
        /// </summary>
        public static string ErrorMessage_IfConditionalCommentNotDeclared {
            get {
                return ResourceManager.GetString("ErrorMessage_IfConditionalCommentNotDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the start tag &lt;{0}&gt; found invalid characters..
        /// </summary>
        public static string ErrorMessage_InvalidCharactersInStartTag {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidCharactersInStartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the text node of XML document found invalid characters..
        /// </summary>
        public static string ErrorMessage_InvalidCharactersInXmlTextNode {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidCharactersInXmlTextNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of &quot;End If conditional comment&quot; does not match to the type of openened &quot;If conditional comment&quot;..
        /// </summary>
        public static string ErrorMessage_InvalidEndIfConditionalComment {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidEndIfConditionalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During minification of {0}-code error has occurred: &quot;{1}&quot;..
        /// </summary>
        public static string ErrorMessage_MarkupMinificationFailed {
            get {
                return ResourceManager.GetString("ErrorMessage_MarkupMinificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During parsing of {0}-code error has occurred..
        /// </summary>
        public static string ErrorMessage_MarkupParsingFailed {
            get {
                return ResourceManager.GetString("ErrorMessage_MarkupParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain not closed conditional comment..
        /// </summary>
        public static string ErrorMessage_NotClosedConditionalComment {
            get {
                return ResourceManager.GetString("ErrorMessage_NotClosedConditionalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag &lt;{0}&gt; was not closed..
        /// </summary>
        public static string ErrorMessage_NotClosedTag {
            get {
                return ResourceManager.GetString("ErrorMessage_NotClosedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is impossible to render a end tag &lt;/{0}&gt;, because  start tag &lt;{0}&gt; not declared..
        /// </summary>
        public static string ErrorMessage_StartTagNotDeclared {
            get {
                return ResourceManager.GetString("ErrorMessage_StartTagNotDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        public static string ErrorMessage_UnknownError {
            get {
                return ResourceManager.GetString("ErrorMessage_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During minification of the XML declaration error has occurred..
        /// </summary>
        public static string ErrorMessage_XmlDeclarationMinificationFailed {
            get {
                return ResourceManager.GetString("ErrorMessage_XmlDeclarationMinificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minification of the {0} code has been completed successfully..
        /// </summary>
        public static string SuccesMessage_MarkupMinificationComplete {
            get {
                return ResourceManager.GetString("SuccesMessage_MarkupMinificationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML-based attribute {0} not allowed here. If you want to use the XHTML syntax, it is better to use XHTML Minifier for minification of this document..
        /// </summary>
        public static string WarningMessage_XmlBasedAttributeNotAllowed {
            get {
                return ResourceManager.GetString("WarningMessage_XmlBasedAttributeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML declaration not allowed here. If you want to use XHTML syntax, it is better to use the XHTML Minifier for minification of this document..
        /// </summary>
        public static string WarningMessage_XmlDeclarationNotAllowed {
            get {
                return ResourceManager.GetString("WarningMessage_XmlDeclarationNotAllowed", resourceCulture);
            }
        }
    }
}
