//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.Matrix.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class index_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal index_cshtml() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.Matrix.App_LocalResources.index.cshtml", typeof(index_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string AddButtonLabel {
            get {
                return ResourceManager.GetString("AddButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matrix Calculator 的本地化字符串。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span style=&quot;color: white; font-size: small; background-color: red; padding: 5px 10px;&quot;&gt;Calculate Online!&lt;/span&gt; 的本地化字符串。
        /// </summary>
        public static string ApplicationNameRemark {
            get {
                return ResourceManager.GetString("ApplicationNameRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add comment 的本地化字符串。
        /// </summary>
        public static string CommentTitle {
            get {
                return ResourceManager.GetString("CommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Results correcting to 的本地化字符串。
        /// </summary>
        public static string DecimalDigitLeftLabel {
            get {
                return ResourceManager.GetString("DecimalDigitLeftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 decimal places. 的本地化字符串。
        /// </summary>
        public static string DecimalDigitRightLabel {
            get {
                return ResourceManager.GetString("DecimalDigitRightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inverse 的本地化字符串。
        /// </summary>
        public static string InverseButtonLabel {
            get {
                return ResourceManager.GetString("InverseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Matrix: 的本地化字符串。
        /// </summary>
        public static string LeftMatrixLabel {
            get {
                return ResourceManager.GetString("LeftMatrixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiply 的本地化字符串。
        /// </summary>
        public static string MultiplyButtonLabel {
            get {
                return ResourceManager.GetString("MultiplyButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Matrix Calculator - Compute Matrix Online! 的本地化字符串。
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result Matrix: 的本地化字符串。
        /// </summary>
        public static string ResultMatrixLabel {
            get {
                return ResourceManager.GetString("ResultMatrixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Matrix: 的本地化字符串。
        /// </summary>
        public static string RightMatrixLabel {
            get {
                return ResourceManager.GetString("RightMatrixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Matrix Calculator - Compute Matrix Online! Easy matrix inputing. Supporting transposing, inversing, addtion, multiplication, subtraction and so on. 的本地化字符串。
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 matrix, calculator, maths, transpose, add, multiply, subtract 的本地化字符串。
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subtract 的本地化字符串。
        /// </summary>
        public static string SubtractButtonLabel {
            get {
                return ResourceManager.GetString("SubtractButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transpose 的本地化字符串。
        /// </summary>
        public static string TransposeButtonLabel {
            get {
                return ResourceManager.GetString("TransposeButtonLabel", resourceCulture);
            }
        }
    }
}
