//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.Apps.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class imageExplorer_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal imageExplorer_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.Apps.App_LocalResources.imageExplorer.cshtml", typeof(imageExplorer_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动滚屏.
        /// </summary>
        public static string auto_scroll_label {
            get {
                return ResourceManager.GetString("auto_scroll_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 美图图片浏览器.
        /// </summary>
        public static string Banner_Title_Text {
            get {
                return ResourceManager.GetString("Banner.Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前 URL：.
        /// </summary>
        public static string current_url_label {
            get {
                return ResourceManager.GetString("current_url_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 去往.
        /// </summary>
        public static string Go_Button_Text {
            get {
                return ResourceManager.GetString("Go.Button.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 走起 &gt;&gt;.
        /// </summary>
        public static string goButtonText {
            get {
                return ResourceManager.GetString("goButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待处理请求：.
        /// </summary>
        public static string http_request_queue_label {
            get {
                return ResourceManager.GetString("http_request_queue_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已发送请求：.
        /// </summary>
        public static string http_request_sent_label {
            get {
                return ResourceManager.GetString("http_request_sent_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已处理图片：.
        /// </summary>
        public static string image_checked_label {
            get {
                return ResourceManager.GetString("image_checked_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待处理图片：.
        /// </summary>
        public static string image_queue_label {
            get {
                return ResourceManager.GetString("image_queue_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂停 ||.
        /// </summary>
        public static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script async src=&quot;//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js&quot;&gt;&lt;/script&gt;
        ///&lt;!-- Image Explorer App Ad --&gt;
        ///&lt;ins class=&quot;adsbygoogle&quot;
        ///     style=&quot;display:inline-block;width:300px;height:600px&quot;
        ///     data-ad-client=&quot;ca-pub-9332882982479681&quot;
        ///     data-ad-slot=&quot;9558341781&quot;&gt;&lt;/ins&gt;
        ///&lt;script&gt;
        ///(adsbygoogle = window.adsbygoogle || []).push({});
        ///&lt;/script&gt;.
        /// </summary>
        public static string Raw_AdZone {
            get {
                return ResourceManager.GetString("Raw_AdZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;只是想看图片，却要不停地“下一页”“下一页”“下一页”……？！每次下一页还要不断跳出多个弹窗，让你手脚忙乱？！想一网打尽美图网站的所有图片而不用一个链接一个链接地点击？&lt;/p&gt;
        ///            &lt;p&gt;哈哈，这个应用帮你解决这些问题！在上面的输入框里输入美图网站的链接，敲回车，然后，就坐在一旁心情观看它所有的图片吧，不费吹灰之力。此应用将大图小图分好了类，方便！宅男福利！&lt;/p&gt;
        ///                &lt;p&gt;应用截图：&lt;/p&gt;
        ///                &lt;p&gt;&lt;img src=&quot;https://lh6.googleusercontent.com/EByn5s2LEPfNx4Q26a9-CLSgOc95NCTQl_Fj5D3LZ1A38v4XEBAi2ll5uwBwd_txtUz94ZDRsQ=s640-h400-e365-rw&quot; alt=&quot;美图图片浏览器&quot;/&gt;&lt;/p&gt;.
        /// </summary>
        public static string Raw_Description {
            get {
                return ResourceManager.GetString("Raw_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 继续 &gt;&gt;.
        /// </summary>
        public static string resume {
            get {
                return ResourceManager.GetString("resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 美图图片浏览器通过自动搜集指定网址的图片，从而直接看图而不再需要下一页下一页不停地点，更不用忙于关闭那些可恶的弹窗了。.
        /// </summary>
        public static string Seo_Description_Text {
            get {
                return ResourceManager.GetString("Seo.Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片,浏览器.
        /// </summary>
        public static string Seo_Keywords_Text {
            get {
                return ResourceManager.GetString("Seo.Keywords.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 美图图片浏览器 - 一网打尽网站美图！.
        /// </summary>
        public static string Seo_Title_Text {
            get {
                return ResourceManager.GetString("Seo.Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态：.
        /// </summary>
        public static string status_label {
            get {
                return ResourceManager.GetString("status_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        public static string stop_button {
            get {
                return ResourceManager.GetString("stop_button", resourceCulture);
            }
        }
    }
}
