//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.Apps.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class matrix_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal matrix_cshtml() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.Apps.App_LocalResources.matrix.cshtml", typeof(matrix_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 加 的本地化字符串。
        /// </summary>
        public static string AddButtonLabel {
            get {
                return ResourceManager.GetString("AddButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线矩阵计算器 的本地化字符串。
        /// </summary>
        public static string BannerText {
            get {
                return ResourceManager.GetString("BannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精确到 的本地化字符串。
        /// </summary>
        public static string DecimalDigitLeftLabel {
            get {
                return ResourceManager.GetString("DecimalDigitLeftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位小数 的本地化字符串。
        /// </summary>
        public static string DecimalDigitRightLabel {
            get {
                return ResourceManager.GetString("DecimalDigitRightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 求逆 的本地化字符串。
        /// </summary>
        public static string InverseButtonLabel {
            get {
                return ResourceManager.GetString("InverseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左矩阵 的本地化字符串。
        /// </summary>
        public static string LeftMatrix {
            get {
                return ResourceManager.GetString("LeftMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/Content/Images/Apps/MatrixLogo.jpg 的本地化字符串。
        /// </summary>
        public static string LogoPath {
            get {
                return ResourceManager.GetString("LogoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;a href=&quot;#&quot; onclick=&quot;return false;&quot; title=&quot;矩阵计算器&quot;&gt;&lt;img src=&quot;{0}&quot; alt=&quot;矩阵计算器&quot; /&gt;&lt;/a&gt; 的本地化字符串。
        /// </summary>
        public static string LogoRaw {
            get {
                return ResourceManager.GetString("LogoRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 乘 的本地化字符串。
        /// </summary>
        public static string MultiplyButtonLabel {
            get {
                return ResourceManager.GetString("MultiplyButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线矩阵计算 的本地化字符串。
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果矩阵 的本地化字符串。
        /// </summary>
        public static string ResultMatrix {
            get {
                return ResourceManager.GetString("ResultMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右矩阵 的本地化字符串。
        /// </summary>
        public static string RightMatrix {
            get {
                return ResourceManager.GetString("RightMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线矩阵计算 —— 求逆、转置、加、减、乘、除。 的本地化字符串。
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 矩阵,求逆,转置,加,减,乘,除 的本地化字符串。
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 减 的本地化字符串。
        /// </summary>
        public static string SubtractButtonLabel {
            get {
                return ResourceManager.GetString("SubtractButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转置 的本地化字符串。
        /// </summary>
        public static string TransposeButtonLabel {
            get {
                return ResourceManager.GetString("TransposeButtonLabel", resourceCulture);
            }
        }
    }
}
