//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.Apps.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class matrix_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal matrix_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.Apps.App_LocalResources.matrix.cshtml", typeof(matrix_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加.
        /// </summary>
        public static string AddButtonLabel {
            get {
                return ResourceManager.GetString("AddButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线矩阵计算器.
        /// </summary>
        public static string BannerText {
            get {
                return ResourceManager.GetString("BannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精确到.
        /// </summary>
        public static string DecimalDigitLeftLabel {
            get {
                return ResourceManager.GetString("DecimalDigitLeftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位小数.
        /// </summary>
        public static string DecimalDigitRightLabel {
            get {
                return ResourceManager.GetString("DecimalDigitRightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 求逆.
        /// </summary>
        public static string InverseButtonLabel {
            get {
                return ResourceManager.GetString("InverseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左矩阵.
        /// </summary>
        public static string LeftMatrix {
            get {
                return ResourceManager.GetString("LeftMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/Apps/MatrixLogo.jpg.
        /// </summary>
        public static string LogoPath {
            get {
                return ResourceManager.GetString("LogoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;#&quot; onclick=&quot;return false;&quot; title=&quot;矩阵计算器&quot;&gt;&lt;img src=&quot;{0}&quot; alt=&quot;矩阵计算器&quot; /&gt;&lt;/a&gt;.
        /// </summary>
        public static string LogoRaw {
            get {
                return ResourceManager.GetString("LogoRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乘.
        /// </summary>
        public static string MultiplyButtonLabel {
            get {
                return ResourceManager.GetString("MultiplyButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线矩阵计算.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果矩阵.
        /// </summary>
        public static string ResultMatrix {
            get {
                return ResourceManager.GetString("ResultMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右矩阵.
        /// </summary>
        public static string RightMatrix {
            get {
                return ResourceManager.GetString("RightMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线矩阵计算 —— 求逆、转置、加、减、乘、除。.
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 矩阵,求逆,转置,加,减,乘,除.
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 减.
        /// </summary>
        public static string SubtractButtonLabel {
            get {
                return ResourceManager.GetString("SubtractButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转置.
        /// </summary>
        public static string TransposeButtonLabel {
            get {
                return ResourceManager.GetString("TransposeButtonLabel", resourceCulture);
            }
        }
    }
}
