//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.Apps.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ploter_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ploter_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.Apps.App_LocalResources.ploter.cshtml", typeof(ploter_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据描点器 —— 散点图、统计计算、趋势拟合，一步到位！.
        /// </summary>
        public static string BannerText {
            get {
                return ResourceManager.GetString("BannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除.
        /// </summary>
        public static string ClearButtonText {
            get {
                return ResourceManager.GetString("ClearButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭消息.
        /// </summary>
        public static string CloseMsg {
            get {
                return ResourceManager.GetString("CloseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭统计计算信息窗口.
        /// </summary>
        public static string CloseStats {
            get {
                return ResourceManager.GetString("CloseStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭帮助.
        /// </summary>
        public static string CloseTips {
            get {
                return ResourceManager.GetString("CloseTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请&lt;strong style=&quot;font-size: larger;&quot;&gt;粘贴&lt;/strong&gt;或输入数据：.
        /// </summary>
        public static string InputLabel {
            get {
                return ResourceManager.GetString("InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/Apps/PloterLogo.jpg.
        /// </summary>
        public static string LogoPath {
            get {
                return ResourceManager.GetString("LogoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;#&quot; onclick=&quot;return false;&quot; title=&quot;在线统计计算器&quot;&gt;&lt;img src=&quot;{0}&quot; alt=&quot;在线统计计算器&quot; /&gt;&lt;/a&gt;.
        /// </summary>
        public static string LogoRaw {
            get {
                return ResourceManager.GetString("LogoRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线数据描点 - 散点图、统计计算、趋势拟合，一步到位！.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描点.
        /// </summary>
        public static string PlotButtonText {
            get {
                return ResourceManager.GetString("PlotButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线数据描点 - 描点、统计计算、趋势拟合，一步到位！线性回归、多项式拟合、趋势拟合、统计量计算。.
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据描点,统计计算,趋势拟合,线性拟合,多项式拟合.
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color: #009900;&quot;&gt;三次函数拟合&lt;/span&gt;.
        /// </summary>
        public static string ShowCubicFit {
            get {
                return ResourceManager.GetString("ShowCubicFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color: #000099;&quot;&gt;指数拟合&lt;/span&gt;.
        /// </summary>
        public static string ShowExpFit {
            get {
                return ResourceManager.GetString("ShowExpFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        public static string ShowHelp {
            get {
                return ResourceManager.GetString("ShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图例.
        /// </summary>
        public static string ShowLegend {
            get {
                return ResourceManager.GetString("ShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color: #FF0000;&quot;&gt;线性拟合&lt;/span&gt;.
        /// </summary>
        public static string ShowLinearFit {
            get {
                return ResourceManager.GetString("ShowLinearFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color: #990000;&quot;&gt;二次函数拟合&lt;/span&gt;.
        /// </summary>
        public static string ShowQuadraticFit {
            get {
                return ResourceManager.GetString("ShowQuadraticFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计计算.
        /// </summary>
        public static string ShowStats {
            get {
                return ResourceManager.GetString("ShowStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;在数据框内输入数据点列。点击“描点”按钮，散点图轻松完成。&lt;/p&gt;
        ///&lt;p&gt;所谓数据点，即x y数据的配对。如1 2就是一个数据点，其横坐标为1，其纵坐标为2。数据点的横、纵坐标值可以用空格、逗号或者分号分隔，即如下输入都是有效的数据点：&lt;/p&gt;
        ///&lt;ul&gt;&lt;li&gt;1 2&lt;/li&gt;
        ///&lt;li&gt;1,2&lt;/li&gt;
        ///&lt;li&gt;1;2&lt;/li&gt;&lt;/ul&gt;
        ///&lt;p&gt;一行输入一个数据点，即组成了一个数据点列。大多数情况下，你可以将做好的表格里的数据直接复制粘贴到这里，非常方便。&lt;/p&gt;.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
    }
}
