//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiZhuJY.Web.UI.Views.Apps.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ploter_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ploter_cshtml() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiZhuJY.Web.UI.Views.Apps.App_LocalResources.ploter.cshtml", typeof(ploter_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 数据描点器 —— 散点图、统计计算、趋势拟合，一步到位！ 的本地化字符串。
        /// </summary>
        public static string BannerText {
            get {
                return ResourceManager.GetString("BannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        public static string ClearButtonText {
            get {
                return ResourceManager.GetString("ClearButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭消息 的本地化字符串。
        /// </summary>
        public static string CloseMsg {
            get {
                return ResourceManager.GetString("CloseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭统计计算信息窗口 的本地化字符串。
        /// </summary>
        public static string CloseStats {
            get {
                return ResourceManager.GetString("CloseStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭帮助 的本地化字符串。
        /// </summary>
        public static string CloseTips {
            get {
                return ResourceManager.GetString("CloseTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请&lt;strong style=&quot;font-size: larger;&quot;&gt;粘贴&lt;/strong&gt;或输入数据： 的本地化字符串。
        /// </summary>
        public static string InputLabel {
            get {
                return ResourceManager.GetString("InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/Content/Images/Apps/PloterLogo.jpg 的本地化字符串。
        /// </summary>
        public static string LogoPath {
            get {
                return ResourceManager.GetString("LogoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;a href=&quot;#&quot; onclick=&quot;return false;&quot; title=&quot;在线统计计算器&quot;&gt;&lt;img src=&quot;{0}&quot; alt=&quot;在线统计计算器&quot; /&gt;&lt;/a&gt; 的本地化字符串。
        /// </summary>
        public static string LogoRaw {
            get {
                return ResourceManager.GetString("LogoRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线数据描点 - 散点图、统计计算、趋势拟合，一步到位！ 的本地化字符串。
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描点 的本地化字符串。
        /// </summary>
        public static string PlotButtonText {
            get {
                return ResourceManager.GetString("PlotButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线数据描点 - 描点、统计计算、趋势拟合，一步到位！线性回归、多项式拟合、趋势拟合、统计量计算。 的本地化字符串。
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据描点,统计计算,趋势拟合,线性拟合,多项式拟合 的本地化字符串。
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span style=&quot;color: #009900;&quot;&gt;三次函数拟合&lt;/span&gt; 的本地化字符串。
        /// </summary>
        public static string ShowCubicFit {
            get {
                return ResourceManager.GetString("ShowCubicFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span style=&quot;color: #000099;&quot;&gt;指数拟合&lt;/span&gt; 的本地化字符串。
        /// </summary>
        public static string ShowExpFit {
            get {
                return ResourceManager.GetString("ShowExpFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        public static string ShowHelp {
            get {
                return ResourceManager.GetString("ShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图例 的本地化字符串。
        /// </summary>
        public static string ShowLegend {
            get {
                return ResourceManager.GetString("ShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span style=&quot;color: #FF0000;&quot;&gt;线性拟合&lt;/span&gt; 的本地化字符串。
        /// </summary>
        public static string ShowLinearFit {
            get {
                return ResourceManager.GetString("ShowLinearFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span style=&quot;color: #990000;&quot;&gt;二次函数拟合&lt;/span&gt; 的本地化字符串。
        /// </summary>
        public static string ShowQuadraticFit {
            get {
                return ResourceManager.GetString("ShowQuadraticFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计计算 的本地化字符串。
        /// </summary>
        public static string ShowStats {
            get {
                return ResourceManager.GetString("ShowStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;p&gt;在数据框内输入数据点列。点击“描点”按钮，散点图轻松完成。&lt;/p&gt;
        ///&lt;p&gt;所谓数据点，即x y数据的配对。如1 2就是一个数据点，其横坐标为1，其纵坐标为2。数据点的横、纵坐标值可以用空格、逗号或者分号分隔，即如下输入都是有效的数据点：&lt;/p&gt;
        ///&lt;ul&gt;&lt;li&gt;1 2&lt;/li&gt;
        ///&lt;li&gt;1,2&lt;/li&gt;
        ///&lt;li&gt;1;2&lt;/li&gt;&lt;/ul&gt;
        ///&lt;p&gt;一行输入一个数据点，即组成了一个数据点列。大多数情况下，你可以将做好的表格里的数据直接复制粘贴到这里，非常方便。&lt;/p&gt; 的本地化字符串。
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
    }
}
